export enum TransactionStep {
  START_TRANSACTION = 'START_TRANSACTION',
  APPROVING_TRANSACTION = 'APPROVING_TRANSACTION',
  PENDING_TRANSACTION = 'PENDING_TRANSACTION',
  COMPLETED_TRANSACTION = 'COMPLETED_TRANSACTION',
  FAILED_TRANSACTION = 'FAILED_TRANSACTION',
  LONG_TRANSACTION = 'LONG_TRANSACTION',
}
