// This file is autogenerated. Run "yarn run-translations" in order to regenerate it

import accountEN from './en/account.json';
import auctionsEN from './en/auctions.json';
import buySellFundFormEN from './en/buy-sell-fund-form.json';
import buySellModalEN from './en/buy-sell-modal.json';
import commonEN from './en/common.json';
import companyEN from './en/company.json';
import componentsEN from './en/components.json';
import exploreEN from './en/explore.json';
import faqEN from './en/faq.json';
import feeControlsEN from './en/fee-controls.json';
import filtersEN from './en/filters.json';
import footerEN from './en/footer.json';
import formsEN from './en/forms.json';
import fundDetailsEN from './en/fund-details.json';
import homeFeedEN from './en/home-feed.json';
import homeEN from './en/home.json';
import integrationsEN from './en/integrations.json';
import issueAndRedeemEN from './en/issue-and-redeem.json';
import loginModalEN from './en/login-modal.json';
import navbarEN from './en/navbar.json';
import onboardingEN from './en/onboarding.json';
import rebalancingNotificationsEN from './en/rebalancing-notifications.json';
import securityEN from './en/security.json';
import sendSetModalEN from './en/send-set-modal.json';
import setDetailsEN from './en/set-details.json';
import socialTraderLandingEN from './en/social-trader-landing.json';
import traderProfileEN from './en/trader-profile.json';

import accountZH from './zh/account.json';
import auctionsZH from './zh/auctions.json';
import buySellFundFormZH from './zh/buy-sell-fund-form.json';
import buySellModalZH from './zh/buy-sell-modal.json';
import commonZH from './zh/common.json';
import companyZH from './zh/company.json';
import componentsZH from './zh/components.json';
import exploreZH from './zh/explore.json';
import faqZH from './zh/faq.json';
import feeControlsZH from './zh/fee-controls.json';
import filtersZH from './zh/filters.json';
import footerZH from './zh/footer.json';
import formsZH from './zh/forms.json';
import fundDetailsZH from './zh/fund-details.json';
import homeFeedZH from './zh/home-feed.json';
import homeZH from './zh/home.json';
import integrationsZH from './zh/integrations.json';
import issueAndRedeemZH from './zh/issue-and-redeem.json';
import loginModalZH from './zh/login-modal.json';
import navbarZH from './zh/navbar.json';
import onboardingZH from './zh/onboarding.json';
import rebalancingNotificationsZH from './zh/rebalancing-notifications.json';
import sendSetModalZH from './zh/send-set-modal.json';
import setDetailsZH from './zh/set-details.json';
import socialTraderLandingZH from './zh/social-trader-landing.json';
import traderProfileZH from './zh/trader-profile.json';

import accountTR from './tr/account.json';
import auctionsTR from './tr/auctions.json';
import buySellFundFormTR from './tr/buy-sell-fund-form.json';
import buySellModalTR from './tr/buy-sell-modal.json';
import commonTR from './tr/common.json';
import companyTR from './tr/company.json';
import componentsTR from './tr/components.json';
import exploreTR from './tr/explore.json';
import faqTR from './tr/faq.json';
import feeControlsTR from './tr/fee-controls.json';
import filtersTR from './tr/filters.json';
import footerTR from './tr/footer.json';
import formsTR from './tr/forms.json';
import fundDetailsTR from './tr/fund-details.json';
import homeFeedTR from './tr/home-feed.json';
import homeTR from './tr/home.json';
import integrationsTR from './tr/integrations.json';
import issueAndRedeemTR from './tr/issue-and-redeem.json';
import loginModalTR from './tr/login-modal.json';
import navbarTR from './tr/navbar.json';
import onboardingTR from './tr/onboarding.json';
import rebalancingNotificationsTR from './tr/rebalancing-notifications.json';
import sendSetModalTR from './tr/send-set-modal.json';
import setDetailsTR from './tr/set-details.json';
import socialTraderLandingTR from './tr/social-trader-landing.json';
import traderProfileTR from './tr/trader-profile.json';

import accountRU from './ru/account.json';
import auctionsRU from './ru/auctions.json';
import buySellFundFormRU from './ru/buy-sell-fund-form.json';
import buySellModalRU from './ru/buy-sell-modal.json';
import commonRU from './ru/common.json';
import companyRU from './ru/company.json';
import componentsRU from './ru/components.json';
import exploreRU from './ru/explore.json';
import faqRU from './ru/faq.json';
import feeControlsRU from './ru/fee-controls.json';
import filtersRU from './ru/filters.json';
import footerRU from './ru/footer.json';
import formsRU from './ru/forms.json';
import fundDetailsRU from './ru/fund-details.json';
import homeFeedRU from './ru/home-feed.json';
import homeRU from './ru/home.json';
import integrationsRU from './ru/integrations.json';
import issueAndRedeemRU from './ru/issue-and-redeem.json';
import loginModalRU from './ru/login-modal.json';
import navbarRU from './ru/navbar.json';
import onboardingRU from './ru/onboarding.json';
import rebalancingNotificationsRU from './ru/rebalancing-notifications.json';
import sendSetModalRU from './ru/send-set-modal.json';
import setDetailsRU from './ru/set-details.json';
import socialTraderLandingRU from './ru/social-trader-landing.json';
import traderProfileRU from './ru/trader-profile.json';

import accountDE from './de/account.json';
import auctionsDE from './de/auctions.json';
import buySellFundFormDE from './de/buy-sell-fund-form.json';
import buySellModalDE from './de/buy-sell-modal.json';
import commonDE from './de/common.json';
import companyDE from './de/company.json';
import componentsDE from './de/components.json';
import exploreDE from './de/explore.json';
import faqDE from './de/faq.json';
import feeControlsDE from './de/fee-controls.json';
import filtersDE from './de/filters.json';
import footerDE from './de/footer.json';
import formsDE from './de/forms.json';
import fundDetailsDE from './de/fund-details.json';
import homeFeedDE from './de/home-feed.json';
import homeDE from './de/home.json';
import integrationsDE from './de/integrations.json';
import issueAndRedeemDE from './de/issue-and-redeem.json';
import loginModalDE from './de/login-modal.json';
import navbarDE from './de/navbar.json';
import onboardingDE from './de/onboarding.json';
import rebalancingNotificationsDE from './de/rebalancing-notifications.json';
import sendSetModalDE from './de/send-set-modal.json';
import setDetailsDE from './de/set-details.json';
import socialTraderLandingDE from './de/social-trader-landing.json';
import traderProfileDE from './de/trader-profile.json';

import accountJA from './ja/account.json';
import auctionsJA from './ja/auctions.json';
import buySellFundFormJA from './ja/buy-sell-fund-form.json';
import buySellModalJA from './ja/buy-sell-modal.json';
import commonJA from './ja/common.json';
import companyJA from './ja/company.json';
import componentsJA from './ja/components.json';
import exploreJA from './ja/explore.json';
import faqJA from './ja/faq.json';
import feeControlsJA from './ja/fee-controls.json';
import filtersJA from './ja/filters.json';
import footerJA from './ja/footer.json';
import formsJA from './ja/forms.json';
import fundDetailsJA from './ja/fund-details.json';
import homeFeedJA from './ja/home-feed.json';
import homeJA from './ja/home.json';
import integrationsJA from './ja/integrations.json';
import issueAndRedeemJA from './ja/issue-and-redeem.json';
import loginModalJA from './ja/login-modal.json';
import navbarJA from './ja/navbar.json';
import onboardingJA from './ja/onboarding.json';
import rebalancingNotificationsJA from './ja/rebalancing-notifications.json';
import sendSetModalJA from './ja/send-set-modal.json';
import setDetailsJA from './ja/set-details.json';
import socialTraderLandingJA from './ja/social-trader-landing.json';
import traderProfileJA from './ja/trader-profile.json';

import accountES_419 from './es_419/account.json';
import auctionsES_419 from './es_419/auctions.json';
import buySellFundFormES_419 from './es_419/buy-sell-fund-form.json';
import buySellModalES_419 from './es_419/buy-sell-modal.json';
import commonES_419 from './es_419/common.json';
import companyES_419 from './es_419/company.json';
import componentsES_419 from './es_419/components.json';
import exploreES_419 from './es_419/explore.json';
import faqES_419 from './es_419/faq.json';
import feeControlsES_419 from './es_419/fee-controls.json';
import filtersES_419 from './es_419/filters.json';
import footerES_419 from './es_419/footer.json';
import formsES_419 from './es_419/forms.json';
import fundDetailsES_419 from './es_419/fund-details.json';
import homeFeedES_419 from './es_419/home-feed.json';
import homeES_419 from './es_419/home.json';
import integrationsES_419 from './es_419/integrations.json';
import issueAndRedeemES_419 from './es_419/issue-and-redeem.json';
import loginModalES_419 from './es_419/login-modal.json';
import navbarES_419 from './es_419/navbar.json';
import onboardingES_419 from './es_419/onboarding.json';
import rebalancingNotificationsES_419 from './es_419/rebalancing-notifications.json';
import sendSetModalES_419 from './es_419/send-set-modal.json';
import setDetailsES_419 from './es_419/set-details.json';
import socialTraderLandingES_419 from './es_419/social-trader-landing.json';
import traderProfileES_419 from './es_419/trader-profile.json';

// This file loads and defines the namespaces for usage in components.
// The key is the namespace for a given language.
// E.g. A component will call withTranslation('navbar') for access to /navbar.json strings.

export default {
  en: {
    account: accountEN,
    auctions: auctionsEN,
    'buy-sell-fund-form': buySellFundFormEN,
    'buy-sell-modal': buySellModalEN,
    common: commonEN,
    company: companyEN,
    components: componentsEN,
    explore: exploreEN,
    faq: faqEN,
    'fee-controls': feeControlsEN,
    filters: filtersEN,
    footer: footerEN,
    forms: formsEN,
    'fund-details': fundDetailsEN,
    'home-feed': homeFeedEN,
    home: homeEN,
    integrations: integrationsEN,
    'issue-and-redeem': issueAndRedeemEN,
    'login-modal': loginModalEN,
    navbar: navbarEN,
    onboarding: onboardingEN,
    'rebalancing-notifications': rebalancingNotificationsEN,
    security: securityEN,
    'send-set-modal': sendSetModalEN,
    'set-details': setDetailsEN,
    'social-trader-landing': socialTraderLandingEN,
    'trader-profile': traderProfileEN,
  },
  zh: {
    account: accountZH,
    auctions: auctionsZH,
    'buy-sell-fund-form': buySellFundFormZH,
    'buy-sell-modal': buySellModalZH,
    common: commonZH,
    company: companyZH,
    components: componentsZH,
    explore: exploreZH,
    faq: faqZH,
    'fee-controls': feeControlsZH,
    filters: filtersZH,
    footer: footerZH,
    forms: formsZH,
    'fund-details': fundDetailsZH,
    'home-feed': homeFeedZH,
    home: homeZH,
    integrations: integrationsZH,
    'issue-and-redeem': issueAndRedeemZH,
    'login-modal': loginModalZH,
    navbar: navbarZH,
    onboarding: onboardingZH,
    'rebalancing-notifications': rebalancingNotificationsZH,
    'send-set-modal': sendSetModalZH,
    'set-details': setDetailsZH,
    'social-trader-landing': socialTraderLandingZH,
    'trader-profile': traderProfileZH,
  },
  tr: {
    account: accountTR,
    auctions: auctionsTR,
    'buy-sell-fund-form': buySellFundFormTR,
    'buy-sell-modal': buySellModalTR,
    common: commonTR,
    company: companyTR,
    components: componentsTR,
    explore: exploreTR,
    faq: faqTR,
    'fee-controls': feeControlsTR,
    filters: filtersTR,
    footer: footerTR,
    forms: formsTR,
    'fund-details': fundDetailsTR,
    'home-feed': homeFeedTR,
    home: homeTR,
    integrations: integrationsTR,
    'issue-and-redeem': issueAndRedeemTR,
    'login-modal': loginModalTR,
    navbar: navbarTR,
    onboarding: onboardingTR,
    'rebalancing-notifications': rebalancingNotificationsTR,
    'send-set-modal': sendSetModalTR,
    'set-details': setDetailsTR,
    'social-trader-landing': socialTraderLandingTR,
    'trader-profile': traderProfileTR,
  },
  ru: {
    account: accountRU,
    auctions: auctionsRU,
    'buy-sell-fund-form': buySellFundFormRU,
    'buy-sell-modal': buySellModalRU,
    common: commonRU,
    company: companyRU,
    components: componentsRU,
    explore: exploreRU,
    faq: faqRU,
    'fee-controls': feeControlsRU,
    filters: filtersRU,
    footer: footerRU,
    forms: formsRU,
    'fund-details': fundDetailsRU,
    'home-feed': homeFeedRU,
    home: homeRU,
    integrations: integrationsRU,
    'issue-and-redeem': issueAndRedeemRU,
    'login-modal': loginModalRU,
    navbar: navbarRU,
    onboarding: onboardingRU,
    'rebalancing-notifications': rebalancingNotificationsRU,
    'send-set-modal': sendSetModalRU,
    'set-details': setDetailsRU,
    'social-trader-landing': socialTraderLandingRU,
    'trader-profile': traderProfileRU,
  },
  de: {
    account: accountDE,
    auctions: auctionsDE,
    'buy-sell-fund-form': buySellFundFormDE,
    'buy-sell-modal': buySellModalDE,
    common: commonDE,
    company: companyDE,
    components: componentsDE,
    explore: exploreDE,
    faq: faqDE,
    'fee-controls': feeControlsDE,
    filters: filtersDE,
    footer: footerDE,
    forms: formsDE,
    'fund-details': fundDetailsDE,
    'home-feed': homeFeedDE,
    home: homeDE,
    integrations: integrationsDE,
    'issue-and-redeem': issueAndRedeemDE,
    'login-modal': loginModalDE,
    navbar: navbarDE,
    onboarding: onboardingDE,
    'rebalancing-notifications': rebalancingNotificationsDE,
    'send-set-modal': sendSetModalDE,
    'set-details': setDetailsDE,
    'social-trader-landing': socialTraderLandingDE,
    'trader-profile': traderProfileDE,
  },
  ja: {
    account: accountJA,
    auctions: auctionsJA,
    'buy-sell-fund-form': buySellFundFormJA,
    'buy-sell-modal': buySellModalJA,
    common: commonJA,
    company: companyJA,
    components: componentsJA,
    explore: exploreJA,
    faq: faqJA,
    'fee-controls': feeControlsJA,
    filters: filtersJA,
    footer: footerJA,
    forms: formsJA,
    'fund-details': fundDetailsJA,
    'home-feed': homeFeedJA,
    home: homeJA,
    integrations: integrationsJA,
    'issue-and-redeem': issueAndRedeemJA,
    'login-modal': loginModalJA,
    navbar: navbarJA,
    onboarding: onboardingJA,
    'rebalancing-notifications': rebalancingNotificationsJA,
    'send-set-modal': sendSetModalJA,
    'set-details': setDetailsJA,
    'social-trader-landing': socialTraderLandingJA,
    'trader-profile': traderProfileJA,
  },
  es_419: {
    account: accountES_419,
    auctions: auctionsES_419,
    'buy-sell-fund-form': buySellFundFormES_419,
    'buy-sell-modal': buySellModalES_419,
    common: commonES_419,
    company: companyES_419,
    components: componentsES_419,
    explore: exploreES_419,
    faq: faqES_419,
    'fee-controls': feeControlsES_419,
    filters: filtersES_419,
    footer: footerES_419,
    forms: formsES_419,
    'fund-details': fundDetailsES_419,
    'home-feed': homeFeedES_419,
    home: homeES_419,
    integrations: integrationsES_419,
    'issue-and-redeem': issueAndRedeemES_419,
    'login-modal': loginModalES_419,
    navbar: navbarES_419,
    onboarding: onboardingES_419,
    'rebalancing-notifications': rebalancingNotificationsES_419,
    'send-set-modal': sendSetModalES_419,
    'set-details': setDetailsES_419,
    'social-trader-landing': socialTraderLandingES_419,
    'trader-profile': traderProfileES_419,
  },
};
